version: '2.1'
services:

    # neo4j:
    #     build:
    #       context: .
    #       dockerfile: Dockerfile.neo4j
    #       args:
    #         - USER_UID=1001
    #         - USER_GID=1001
    #     image: neo4j-n10s:latest
    #     environment:
    #         - NEO4J_AUTH=none
    #     ports:
    #         - "7474:7474"
    #         - "7687:7687"
    #     volumes:
    #         - ~/.neo4j/data:/data
    #         - ~/.neo4j/import:/var/lib/neo4j/import
    #         - ~/.neo4j/logs:/logs
    #         - ./config/test/dumps:/dumps

    # virtuoso:
    #     image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    #     environment:
    #       SPARQL_UPDATE: "true"
    #       DEFAULT_GRAPH: "http://www.example.com/my-graph"
    #       VIRT_Parameters_DirsAllowed: "/data/dumps"
    #     volumes:
    #       - ~/.virtuoso:/data
    #       - ./dags_test_data/shared_dir:/data/dumps
    #     ports:
    #       - "8890:8890"

    rdfox:
      image: oxfordsemantic/rdfox
      volumes:
        - ./RDFox-data/RDFox.lic:/opt/RDFox/RDFox.lic
        - ./rdfox-server-directory:/home/rdfox/.RDFox
        - ./RDFox-data:/data
      # environment:
      #   RDFOX_ROLE: admin
      #   RDFOX_PASSWORD: leca2019
      cap_drop:
        - ALL
      ports:
        - "12110:12110"

    # graphdb:
    #     image: ontotext/graphdb:9.3.3-free
    #     ports:
    #         - "7200:7200"
    #     volumes:
    #         - .graphdb/:/opt/graphdb/home/data/
    #         - ./dags_test_data/:/opt/graphdb/home/data/

    # anzograph:
    #     build:
    #           context: .
    #           dockerfile: Dockerfile.anzograph
    #           args:
    #             - USER_UID=1001
    #             - USER_GID=1001
    #     image: cambridgesemantics/anzograph:latest
    #     ports:
    #         - "8081:8080"
    #         - "8443:8443"virtuoso
    #     volumes:
    #         - ./dags_test_data/:/opt/shared-directory

    # yarrrmlmapper:
    #     build: https://github.com/RMLio/yarrrml-rmlmapper-docker.git#:docker
    #     image: yarrrmlmapper
    #     volumes:


    # nomer:
    #     build: https://github.com/nleguillarme/nomer-docker.git
    #     image: nomer-docker
    #     ports:
    #         - "5000:5000"
    #     volumes:
    #         - .tmp/.nomer:/.nomer

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build:
          context: .
          dockerfile: Dockerfile.airflow
          args:
            - DOCKER_UID=1001
            - DOCKER_GID=999
        image: custom-airflow
        #restart: always
        depends_on:
            - postgres
            #- nomer
            - rdfox
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
            - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
            - AIRFLOW__WEBSERVER__DAG_ORIENTATION=TB
            - EXECUTOR=Local
        volumes:
            - .:/usr/local/airflow/dags
            - ./jars:/usr/local/airflow/jars
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
