version: '3.8'

services:

  nomer:
    build:
      context: ${INTEGRAPH__INSTALL__INSTALL_DIR}
      dockerfile: Dockerfile.nomer
    image: nomer:latest

  gnparser:
    image: gnames/gognparser:latest
    ports:
      - "8778:8778"

  mapeathor:
    build:
      context: ${INTEGRAPH__INSTALL__INSTALL_DIR}
      dockerfile: Dockerfile.mapeathor
    image: mapeathor:latest

  morph-kgc:
    build:
      context: ${INTEGRAPH__INSTALL__INSTALL_DIR}
      dockerfile: Dockerfile.morph_kgc
    image: morph-kgc:latest
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=airflow
  #     - POSTGRES_PASSWORD=airflow
  #     - POSTGRES_DB=airflow

  # webserver:
  #   build:
  #     context: ${INTEGRAPH__INSTALL__INSTALL_DIR}
  #     dockerfile: Dockerfile.airflow
  #     args:
  #       - DOCKER_UID=${INTEGRAPH__CONFIG__USER_ID}
  #       - DOCKER_GID=${INTEGRAPH__CONFIG__DOCKER_GROUP_ID}
  #   image: custom-airflow
  #   restart: on-failure
  #   depends_on:
  #     - postgres
  #     - gnparser
  #     - nomer
  #     - mapeathor
  #     - morph-kgc
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
  #     - AIRFLOW__CORE__LOAD_EXAMPLES=False
  #     - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
  #     - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
  #     - AIRFLOW__WEBSERVER__AUTHENTICATE=False
  #     - USER_UID=${INTEGRAPH__CONFIG__USER_ID}
  #     - GROUP_UID=${INTEGRAPH__CONFIG__GROUP_ID}
  #     - INTEGRAPH__CONFIG__NOMER_CACHE_DIR=${INTEGRAPH__CONFIG__NOMER_CACHE_DIR}
  #     - INTEGRAPH__CONFIG__HOST_CONFIG_DIR=${INTEGRAPH__CONFIG__HOST_CONFIG_DIR}
  #     - INTEGRAPH__CONFIG__ROOT_CONFIG_DIR=/opt/airflow/config
  #     - INTEGRAPH__EXEC__TEST_MODE=${INTEGRAPH__EXEC__TEST_MODE}
  #   volumes:
  #     - ${INTEGRAPH__CONFIG__HOST_CONFIG_DIR}:/opt/airflow/config
  #     - ${INTEGRAPH__CONFIG__AIRFLOW_LOGS_DIR}:/opt/airflow/logs
  #     - ${PWD}:/opt/airflow/dags
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /usr/bin/docker:/usr/bin/docker
  #     - /tmp:/tmp
  #     # Uncomment to include custom plugins
  #     # - ./plugins:/usr/local/airflow/plugins
  #   ports:
  #     - "8080:8080"
  #     - "5432:5432"
  #   command: webserver
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "[ -f /usr/local/airflow/airflow-webserver.pid ]"
  #       ]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
