version: '2.1'

services:

    # neo4j:
    #     build:
    #       context: .
    #       dockerfile: Dockerfile.neo4j
    #       args:
    #         - USER_UID=1001
    #         - USER_GID=1001
    #     image: neo4j-n10s:latest
    #     environment:
    #         - NEO4J_AUTH=none
    #     ports:
    #         - "7474:7474"
    #         - "7687:7687"
    #     volumes:
    #         - ~/.neo4j/data:/data
    #         - ~/.neo4j/import:/var/lib/neo4j/import
    #         - ~/.neo4j/logs:/logs
    #         - ./config/test/dumps:/dumps

    # virtuoso:
    #     image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    #     environment:
    #       SPARQL_UPDATE: "true"
    #       DEFAULT_GRAPH: "http://www.example.com/my-graph"
    #       VIRT_Parameters_DirsAllowed: "/data/dumps"
    #     volumes:
    #       - ~/.virtuoso:/data
    #       - ./dags_test_data/shared_dir:/data/dumps
    #     ports:
    #       - "8890:8890"

    # rdfox:
    #   image: oxfordsemantic/rdfox
    #   volumes:
    #     - ${PWD}/RDFox-data/RDFox.lic:/opt/RDFox/RDFox.lic
    #     - ${PWD}/rdfox-server-directory:/home/rdfox/.RDFox
    #   cap_drop:
    #     - ALL
    #   ports:
    #     - "12110:12110"

    graphdb:
      image: ontotext/graphdb:9.8.0-free
      volumes:
        - ${PWD}/graphdb-data:/opt/graphdb/home
      environment:
        GDB_JAVA_OPTS: >-
          -Xmx12g -Xms12g
          -Dgraphdb.home=/opt/graphdb/home
          -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
          -Dgraphdb.workbench.cors.enable=true
          -Denable-context-index=true
          -Dentity-pool-implementation=transactional
          -Dhealth.max.query.time.seconds=60
          -Dgraphdb.append.request.id.headers=true
          -Dreuse.vars.in.subselects=true
      ports:
        - "7200:7200"

    # anzograph:
    #     build:
    #           context: .
    #           dockerfile: Dockerfile.anzograph
    #           args:
    #             - USER_UID=1001
    #             - USER_GID=1001
    #     image: cambridgesemantics/anzograph:latest
    #     ports:
    #         - "8081:8080"
    #         - "8443:8443"
    #     volumes:
    #         - ./dags_test_data/:/opt/shared-directory

    # nomer:
    #     build:
    #       context: ${HOME}/workspace/pynomer
    #       #context: https://github.com/nleguillarme/pynomer.git
    #       dockerfile: Dockerfile
    #     image: pynomer
    #     user: "${USER_ID}:${GROUP_ID}"
    #     ports:
    #         - "9090:9090"
    #     volumes:
    #         - ${NOMER_DIR}:/.nomer

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build:
          context: ./install_files
          dockerfile: Dockerfile.airflow
          args:
            - DOCKER_UID=${USER_ID}
            - DOCKER_GID=999
        # user: ${USER_ID}:${GROUP_ID}
        image: custom-airflow
        restart: on-failure
        depends_on:
            - postgres
            - graphdb
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
            - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
            - AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG
            - AIRFLOW__WEBSERVER__DAG_ORIENTATION=TB
            - AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW=graph
            - AIRFLOW__WEBSERVER__AUTHENTICATE=False
            - INTEGRAPH__CONFIGURATION__CONFIG_DIR=${INTEGRAPH__CONFIGURATION__CONFIG_DIR}
            - USER_UID=${USER_ID}
            - GROUP_UID=${GROUP_ID}
            - INTEGRAPH__CONFIGURATION__NOMER_CACHE_DIR=${NOMER_DIR}
            - INTEGRAPH__EXECUTION__TEST_MODE=${INTEGRAPH__EXECUTION__TEST_MODE}
            - CONFIG_DIR=/opt/airflow/config
            #- AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}"
        volumes:
            # - ${INTEGRAPH__CONFIGURATION__CONFIG_DIR}:/opt/airflow/config
            - shared_config:/opt/airflow/config
            - ${PWD}:/opt/airflow/dags
            - ${HOME}/.integraph/logs:/opt/airflow/logs
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

volumes:
  shared_config:
    driver: local
    driver_opts:
        type: none
        device: ${INTEGRAPH__CONFIGURATION__CONFIG_DIR} #NOTE needs full path (~ doesn't work)
        o: bind
