internal_id : test.csv
properties : tab.properties

# Dataset location : one of (file_location, http_endpoint, sparql_endpoint)
file_location : "file://$CONFIG_DIR/sources/test_csv/data/1.interactions_list_sample.csv"

#file_location : "file://$CONFIG_DIR/sources/test_csv/data/KB_v2.xls"

standard_format : "csv"
delimiter : ","

num_processes : 3
source_root_dir : "$CONFIG_DIR/sources/test_csv"

scheduleInterval : "@once"

graph_uri : https://leca.osug.fr/biodivgraph-test/test.csv
