# db: virtuoso
# container_name: biodivgraph_virtuoso_1
# user_name: dba
# user_password: dba
# shared_dir: shared_dir
# remote_dir: /data/dumps
db: rdfox
rdfox_role: admin
rdfox_password: leca2019
rdfox_host: rdfox
rdfox_port: 12110
rdfox_datastore: biodivgraph-test
shared_dir: shared_dir
